version: '3.7'

services:

  db_app_notes:
    image: postgres 
    container_name: db_app_notes   
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: app_note_db
    volumes:
      - ./src/main/resources/schema/create_tables.sql:/docker-entrypoint-initdb.d/create_tables.sql
    ports:
      - "5432:5432"

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "admin@admin.com"
      PGADMIN_DEFAULT_PASSWORD: "root"
    ports:
      - "5080:80"
    depends_on:
      - db_app_notes
      
          